version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: cryptominer-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - cryptominer-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: cryptominer-backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://admin:password@mongodb:27017/cryptominer?authSource=admin
      - DB_NAME=cryptominer
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app/backend
      - ./logs:/app/logs
    networks:
      - cryptominer-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cryptominer-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/frontend
    networks:
      - cryptominer-network

volumes:
  mongodb_data:
    driver: local

networks:
  cryptominer-network:
    driver: bridge